package assets;

// generated by tiles.blend

import assets.PipelineTools.Anim;
import assets.PipelineTools.Sheet;

@:publicFields enum abstract TileID(Int) from Int to Int {
    var haxeLogo;
    var haxeCat;
    public static var names = ["haxeLogo", "haxeCat"];
    @:from static public function fromString(s:String):TileID return names.indexOf(s);
    public static function iterator() return new IntIterator(0,2);
}

@:publicFields enum abstract AnimID(Int) from Int to Int {
    var rotateMorph;
    var logo;
    var none;
    public static var names = ["rotateMorph", "logo", "none"];
    @:from static public function fromString(s:String):AnimID return names.indexOf(s);
    public static function iterator() return new IntIterator(0,3);
}

// --------- Tiles ----------

interface Tile {
    public var sheet(get, never):Int;
    public var animID:Array<AnimID>;
    public function anim(id:AnimID):Anim;
}

@:publicFields class Haxelogo implements Tile {
    inline function new () {};
    var sheet(get, never):Int; inline function get_sheet() return 0;
    inline function anim(id:AnimID):Anim {
        return switch(id) {
            case rotateMorph: new Anim(0, 35);
            case logo: new Anim(36, 36);
            default: throw("Error, Haxelogo don't have this animation"); null;
        }
    }
    var animID:Array<AnimID> = [rotateMorph, logo];
}
@:publicFields class Haxecat implements Tile {
    inline function new () {};
    var sheet(get, never):Int; inline function get_sheet() return 0;
    inline function anim(id:AnimID):Anim {
        return switch(id) {
            case none: new Anim(37, 37);
            default: throw("Error, Haxecat don't have this animation"); null;
        }
    }
    var animID:Array<AnimID> = [none];
}


class Pipeline {
    public static var sheets:Array<Sheet> = [
        new Sheet("64x64.png", 64, 64, 0, 16, 3),
    ];
    public inline static function tile(id:TileID):Tile {
        return switch(id) {
            case haxeLogo: new Haxelogo();
            case haxeCat: new Haxecat();
            default:  throw("Error, no tile for this ID"); null;
        }
    }
}

